services:
  db:
    image: postgres:15-alpine3.20
    volumes:
      - ./postgres-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: sh -c "cd /home/mysite ;  python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./mysite/:/home/mysite
    ports:
      - "18000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db